name: Retry Step
description: 'Retry a step on failure or timeout'
inputs:
  timeout_minutes:
    description: Minutes to wait before attempt times out.  Must only specify either minutes or seconds
    required: false
  timeout_seconds:
    description: Seconds to wait before attempt times out.  Must only specify either minutes or seconds
    required: false
  max_attempts:
    description: Number of attempts to make before failing the step
    required: true
    default: 3
  command:
    description: The command to run
    required: true
  retry_wait_seconds:
    description: Number of seconds to wait before attempting the next retry
    required: false
    default: 10
  polling_interval_seconds:
    description: Number of seconds to wait for each check that command has completed running
    required: false
    default: 1
  retry_on:
    description: Event to retry on.  Currently supported [any, timeout, error]
    default: any
  hide_output:
    description: Hide console output of command, both stdout and stderr stream.
    default: false
  show_stats:
    description: 'Show statistics on finish: Status, Return Code, Time, Number of printed lines'
    default: false
  save_lines:
    description: 'On finish, print a summary of last N lines of process outputs for every attempt. Value format: num_lines_stdout num_lines_stderr. Use value "all" to show all lines.'
    default: 10 100

outputs:
  total_attempts:
    description: The final number of attempts made
  exit_code:
    description: The final exit code returned by the command
  exit_error:
    description: The final error returned by the command
runs:
  using: 'node12'
  main: 'dist/index.js'
